baseURL = "https://hiepph.xyz/"
languageCode = "en-us"
title = "hiepph"
theme = "nostyleplease"

[params]
  [params.theme_config]
    appearance = "light"
    back_home_text = ".."
    date_format = "Feburary 01, 2006"
